---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@master
      - name: rustfmt check
        run: cargo fmt --all -- --check
